[project]
name = "golkotha-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.3",
    "soccerdata>=1.9.0",
    "statsbombpy>=1.21.0",
]

[dependency-groups]
dev = [
    "notebook>=7.6.0",
    "python-dotenv>=1.2.2",
]
